# -*- coding: utf-8 -*-
"""even odd

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1YmpKIXtMPPnj4BJzxGRCh_yCtlzmzbdd
"""

num= int(input("enter a number: "))
if num % 2 == 0:
  print(num, "is an even number. ")
else:
  print(num, "is an odd number. ")

